server:
  port: 8080
spring:
  application:
    name: hnyh
  servlet:
    multipart:
      max-file-size: 4096MB
      max-request-size: 4096MB
  mvc:
    async:
      request-timeout: 60000

  datasource:
    name: hnyh
    url: jdbc:mysql://101.43.202.11:3306/hnyh?serverTimezone=Asia/Shanghai&autoReconnect=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: hnyhPool # ?????
      minimum-idle: 20 #????????????
      maximum-pool-size: 500 #????????????
      idle-timeout: 30000 #?????????????????????????retired?
      connection-timeout: 20000 #??????????????????
      connection-test-query: SELECT 1 # ?
  redis:
    database: 0
    #host: 127.0.0.1
    #password: 123456
    host: 101.43.202.11
    password: root123
    port: 6379
    pool:
      max-wait: 30000    # ???????????????????????
      max-active: 100   # ????????????????????
      max-idle: 20     # ???????????
      min-idle: 20     # ???????????
    timeout: 20000   # ????